### ISSUE TITLE
[BUG] ReferenceError: AbortController is not defined - no response from bot

### ISSUE THREAD

**Issue by Eleksar387** [Cohee1207/SillyTavern#157]
SillyTavern worked fine for me several hours ago. But I don't get any response anymore from the bot after I enter my message. There is this error message in the terminal:

`ReferenceError: AbortController is not defined
    at /home/jimbo/www/SillyTavern/server.js:2212:24
    at Layer.handle [as handle_request] (/home/jimbo/www/SillyTavern/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jimbo/www/SillyTavern/node_modules/express/lib/router/route.js:144:13)
    at /home/jimbo/www/SillyTavern/node_modules/body-parser/lib/read.js:137:5
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at invokeCallback (/home/jimbo/www/SillyTavern/node_modules/raw-body/index.js:231:16)
    at done (/home/jimbo/www/SillyTavern/node_modules/raw-body/index.js:220:7)
    at IncomingMessage.onEnd (/home/jimbo/www/SillyTavern/node_modules/raw-body/index.js:280:7)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)`

I am running it on WSL2/Win10. Using OpenAi. It is successfully connected. A git pull says I am up-to-date on main.

**Comment by Eleksar387** [comment]
Uh! I am sorry. Of course! I guess I missed to change the node version. Thank you for the extreme quick response and sorry for bothering!!!
