### ISSUE TITLE
[BUG]Invalid or expired token when use poe

### ISSUE THREAD

**Issue by shadowlinyf** [Cohee1207/SillyTavern#193]
version:latest release

ForbiddenError: invalid csrf token
    at doubleCsrf (H:\llm\SillyTavern\SillyTavern-1.4.9\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (H:\llm\SillyTavern\SillyTavern-1.4.9\server.js:166:72)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by shadowlinyf** [comment]
I thought it is related but I still got this.
![image](https://user-images.githubusercontent.com/13216079/235289637-4fb517cb-46c0-4757-982a-6ee88ef4bbdc.png)

**Comment by shadowlinyf** [comment]
> 

No nothing in console window. Any it take almost no time when I input the token and click the button to got this alert,

**Comment by shadowlinyf** [comment]
![image](https://user-images.githubusercontent.com/13216079/235303856-103abf92-2bc6-47f3-bfc7-11dc5a376e6b.png)
![image](https://user-images.githubusercontent.com/13216079/235303921-2d65ecc0-2d10-4c5e-86a0-ab413697e8b7.png)

**Comment by RossAscends** [comment]
We have good reason to believe that this problem is mostly caused by an outdated nodeJS. 

check what version of nodeJS you have installed, and upgrade to at least v18 if it's older than that.
