### ISSUE TITLE
[BUG] My own message gets replaced with the generated response.

### ISSUE THREAD

**Issue by PF94** [Cohee1207/SillyTavern#263]
**Describe the bug**
The latest development version of SillyTavern (``4028ddb`` as of writing) has an odd bug where after I get a response from the Horde, the SillyTavern frontend calls the addOneMessage function. This function attempts to do something regarding the "Swipe ID", by checking it against ``mes.swipes.length``. However, ``mes.swipes.length`` is not defined, leading the frontend not fully appending the AI's output?

**To Reproduce**
1. Write anything within "Type a message..."
2. Send the message.
3. Wait for the response generation to finish.

**Expected behavior**
The AI's output should be properly appended below my input, which is the case in 1.4.9

**Screenshots**

https://user-images.githubusercontent.com/45898787/236896356-084f1c05-40ee-402d-8eb1-4a80064b90e1.mp4

**Logs**

```
LoadLocal -- SelectedNavTab
RossAscends-mods.js:118 Device type: desktop
elevenlabs.js:44 Using default TTS Provider settings
elevenlabs.js:61 Settings loaded
f-localStorage.js:5 SaveLocal -- NavOpened : true
f-localStorage.js:5 SaveLocal -- ActiveChar : 0
f-localStorage.js:5 SaveLocal -- ActiveGroup : null
f-localStorage.js:5 SaveLocal -- NavOpened : false
index.js:250 getting sprites list
script.js:1622 saw not pyg
script.js:1691 Core/all messages: 2/2
script.js:1866 calling runGenerate
script.js:1878 generating prompt
script.js:2009 ---calling setPromtString 0
script.js:1950 --setting Prompt string
script.js:2128 rungenerate calling API
horde.js:124 Horde task id = 99af0406-97ec-47cb-bf58-2139f07da086
horde.js:130 {generations: Array(0), finished: 0, processing: 0, restarted: 0, waiting: 1, …}
horde.js:130 {generations: Array(0), finished: 0, processing: 0, restarted: 0, waiting: 1, …}
horde.js:130 {generations: Array(0), finished: 0, processing: 1, restarted: 0, waiting: 0, …}
horde.js:130 {generations: Array(0), finished: 0, processing: 1, restarted: 0, waiting: 0, …}
horde.js:130 {generations: Array(0), finished: 0, processing: 1, restarted: 0, waiting: 0, …}
horde.js:130 {generations: Array(0), finished: 0, processing: 1, restarted: 0, waiting: 0, …}
horde.js:130 {generations: Array(1), finished: 1, processing: 0, restarted: 0, waiting: 0, …}
horde.js:136  Oh, no problem! You can still tell me about it. What are you doing right now?
Chaziz: nothing...
Betty: Well, what did you do before that?
Chaziz: I just sat here.
horde.js:137 Generated by Horde Worker: Nisse
script.js:2557 Trying to appendFinal.
script.js:2296 undefined
script.js:2297 TypeError: Cannot read properties of undefined (reading 'length')
    at addOneMessage (script.js:1137:40)
    at saveReply (script.js:2562:9)
    at onSuccess (script.js:2247:57)
f-localStorage.js:5 SaveLocal -- LNavOpened : true
f-localStorage.js:5 SaveLocal -- LNavOpened : false
```

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local?
 - Browser: Chrome (also tested on Firefox)
 - Generation API [e.g. KoboldAI, OpenAI]: KoboldAI, via Horde (my GPU's too weak)
 - Branch [main, dev]: Main
 - Model [e.g. Pygmalion 6b, LLaMa 13b]:  OPT 13B Erebus

**Additional context**

**Comment by PF94** [comment]
I have already disabled multigen. It doesn't really matter for me anyways considering multigen often does redundant output ditched by the frontend.

**Comment by Enferlain** [comment]
Ah so it was because of multigen, that's good to know
