### ISSUE TITLE
[BUG] Too many tags causes the tag editor to not open.

### ISSUE THREAD

**Issue by Nephanor-of-Fraal** [Cohee1207/SillyTavern#264]
Not sure how many tags will cause this, as I noticed it when I finished sorting my entire library.  I currently have 52 different tags, taking 5 complete lines and a little bit on a 6th, but I can't bring up the editor window to change tag colors anymore.

**Comment by Nephanor-of-Fraal** [comment]
Either that, or it's the / in some of them

**Comment by Nephanor-of-Fraal** [comment]
Got this error in the browser inspector:
caught Error: Syntax error, unrecognized expression: Ghost/Spirit-tag-color
    at se.error (jquery-3.5.1.min.js:2:13606)
    at se.tokenize (jquery-3.5.1.min.js:2:21617)
    at se.select (jquery-3.5.1.min.js:2:22444)
    at Function.se [as find] (jquery-3.5.1.min.js:2:7089)
    at S.fn.init.find (jquery-3.5.1.min.js:2:25014)
    at new S.fn.init (jquery-3.5.1.min.js:2:25503)
    at S (jquery-3.5.1.min.js:2:1024)
    at HTMLDivElement.onViewTagsListClick (tags.js:323:9)
    at HTMLDocument.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
se.error @ jquery-3.5.1.min.js:2
se.tokenize @ jquery-3.5.1.min.js:2
se.select @ jquery-3.5.1.min.js:2
se @ jquery-3.5.1.min.js:2
find @ jquery-3.5.1.min.js:2
S.fn.init @ jquery-3.5.1.min.js:2
S @ jquery-3.5.1.min.js:2
onViewTagsListClick @ tags.js:323
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
2tags.js:318 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at tags.js:318:56
(anonymous) @ tags.js:318
setTimeout (async)
onViewTagsListClick @ tags.js:317
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
tags.js:318 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#W++-tag-color' is not a valid selector.
    at http://10.75.104.107:8000/scripts/tags.js:318:22
(anonymous) @ tags.js:318
setTimeout (async)
onViewTagsListClick @ tags.js:317
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
6tags.js:318 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at tags.js:318:56
(anonymous) @ tags.js:318
setTimeout (async)
onViewTagsListClick @ tags.js:317
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2
tags.js:318 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#Ghost/Spirit-tag-color' is not a valid selector.
    at http://10.75.104.107:8000/scripts/tags.js:318:22

**Comment by Nephanor-of-Fraal** [comment]
I'll have to let you know....I lost all the tags in the update, so need to re-do them all >.>

**Comment by Nephanor-of-Fraal** [comment]
Yup, it replaced that file.  Gonna back that up this time.
