### ISSUE TITLE
[BUG] UnboundLocalError: local variable 'reply' referenced before assignment

### ISSUE THREAD

**Issue by Priestru** [Cohee1207/SillyTavern#338]
```
INFO:connection open
ERROR:connection handler failed
Traceback (most recent call last):
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "D:\LLM\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
  File "D:\LLM\oobabooga_windows\text-generation-webui\extensions\api\streaming_api.py", line 35, in _handle_connection
    for a in generator:
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 184, in generate_reply
    for reply in generate_func(question, original_question, seed, state, eos_token, stopping_strings, is_chat=is_chat):
  File "D:\LLM\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 316, in generate_reply_custom
    new_tokens = len(encode(original_question + reply)[0]) - original_tokens
UnboundLocalError: local variable 'reply' referenced before assignment
INFO:connection closed
```

I use latest build of SillyTavern with ooba's backend. If i refresh tab and try few times occasionally it would pass and generate as usual. But i get this kind of error quite frequently.

**Comment by Priestru** [comment]
Yes, it's smth on ooba side. Sry.

https://github.com/oobabooga/text-generation-webui/issues/2169

**Comment by Priestru** [comment]
Reducing context size in sillytavern gui to 2k from 2048 completely solved this issue.
