### ISSUE TITLE
[BUG] Crash on startup

### ISSUE THREAD

**Issue by Kaiten10** [Cohee1207/SillyTavern#41]
**Describe the bug**
Crash on startup. The webpage loads, but the server crashes immediately.

**To Reproduce**
1. Run Start.bat
2. Server crashes immediately after opening the webpage.

**Expected behavior**
Start the server without any issues.

**Log**
```
E:\ProgramsE\TavernAI-SillyLossy Mod>call npm install

up to date, audited 194 packages in 659ms

22 packages are looking for funding
  run `npm fund` for details

7 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Launching...
TavernAI started: http://127.0.0.1:8000
E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:680
    var base64DecodedData = Buffer.from(textChunks[0].text, 'base64').toString('utf8');
                                                      ^

TypeError: Cannot read properties of undefined (reading 'text')
    at charaRead (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:680:55)
    at E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:700:28
    at Array.forEach (<anonymous>)
    at E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:698:18
    at FSReqCallback.oncomplete (node:fs:198:23)

Node.js v18.15.0
Press any key to continue . . .
```

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Browser: Firefox
 - Generation API: KoboldAI
 - Branch: main
 - Model: KoboldAI_OPT-13B-Nerybus-Mix

**Additional context**
It has been starting normally last week. It only started crashing when I started it today, I guess because it updated itself to the latest version. It said that there was an update to NPM and it updated itself.

**Comment by Kaiten10** [comment]
I solved it by doing a git pull of the main branch. Keeping this here in case anyone else has this problem.

**Comment by Kaiten10** [comment]
I spoke too soon. The server still crashes on startup, but now it gives another error:

```
Launching...
TavernAI started: http://127.0.0.1:8000
ForbiddenError: invalid csrf token
    at doubleCsrf (E:\ProgramsE\TavernAI-SillyLossy Mod\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:117:72)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (E:\ProgramsE\TavernAI-SillyLossy Mod\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:117:72)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (E:\ProgramsE\TavernAI-SillyLossy Mod\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:117:72)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
ForbiddenError: invalid csrf token
    at doubleCsrf (E:\ProgramsE\TavernAI-SillyLossy Mod\node_modules\csrf-csrf\lib\cjs\index.cjs:18:61)
    at Object.<anonymous> (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:117:72)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:688
    var base64DecodedData = Buffer.from(textChunks[0].text, 'base64').toString('utf8');
                                                      ^

TypeError: Cannot read properties of undefined (reading 'text')
    at charaRead (E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:688:55)
    at E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:708:28
    at Array.forEach (<anonymous>)
    at E:\ProgramsE\TavernAI-SillyLossy Mod\server.js:706:18
    at FSReqCallback.oncomplete (node:fs:198:23)

Node.js v18.15.0
```

**Comment by Kaiten10** [comment]
> Let me know if the issue persists. Closing for now. Thanks,

Thanks! The latest commit fixed the issue.
