### ISSUE TITLE
[BUG] when I try to use with oobabooga (text-generation-webui) I get a #### { error: 'This app has no endpoint /api/textgen/.' }

### ISSUE THREAD

**Issue by baphilia** [Cohee1207/SillyTavern#62]
**Describe the bug**
when I try to use with oobabooga, the first time I type something
I get a #### { error: 'This app has no endpoint /api/textgen/.' } in the Silly Tavern console window.
the ui just stays on a spinning circle, but never generates anything

No debug output in the text-generation-webui window
 
**To Reproduce**
1. Attempt to connect to Text generation web ui
2. Attempt to chat with a bot

**Expected behavior**
To respond

**Screenshots**
![image](https://user-images.githubusercontent.com/115659363/231744063-04684832-41b9-45aa-b547-6ce5d32a491e.png)

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Browser: Brave (chromium)
 - Generation API: text-generation-webui
 - Branch main and dev (just updated dev to latest before writing this bug report
 - Model: Pygmalion 6b

**Additional context**
I made sure to run with --no-stream, and to choose "notebook" under Interface Mode
though there is another mode that lets you choose cai-chat,  chat, or instruct  in the actual chat tab of the ui, and I just chose cai-chat
I tried updating text-generation-webui

**Comment by baphilia** [comment]
> cai-chat and chat modes do not provide an API endpoint, there's nothing I can do about that. You can also try running oobabooga with an API extension, that provides a Kobold-compatible network interface.

> cai-chat and chat modes do not provide an API endpoint, there's nothing I can do about that. You can also try running oobabooga with an API extension, that provides a Kobold-compatible network interface.

I mean I try to use notebook as instructed, which it lets me set in "Interface mode" tab, but on the "Text generation" tab, but within the chat part of the ui there is this:

![image](https://user-images.githubusercontent.com/1701058/231745036-53242422-4819-429f-a9f4-8189ba3b7c39.png)

I'm not sure what to set that to

**Comment by baphilia** [comment]
> Can you try with default mode instead of notebook and/or make sure that the Web UI reloads after you choose the mode?

Totally missed that button.  I wasn't doing "Apply and restart the interface", but when I do, whether I choose "default" or "notebook", it no longer has the extra mode switch, but when I try to type something in chat,  tavern gives the console error:
`#### { error: null }`

and oobabooga gives the console error:
```
Traceback (most recent call last):
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "Z:\repos\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "Z:\repos\oobabooga-windows\text-generation-webui\modules\api.py", line 28, in generate_reply_wrapper
    for i in generate_reply(params[0], generate_params):
  File "Z:\repos\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 175, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
  File "Z:\repos\oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by baphilia** [comment]
> Looks like oobabooga didn't load a tokenizer for your model. Do you have the ability to test with another model?

thank you, it did work with another model.  now I just need to figure out what's up with pygmalion-6b-gptq-4bit.  In any case, thank you very much for your quick help
