### ISSUE TITLE
Text Gen WebUI broken?

### ISSUE THREAD

**Issue by Woipi** [Cohee1207/SillyTavern#83]
**Describe the bug**
SillyTavern crashes after sending the first message. Oobabooga is in default/notebook mode.

**To Reproduce**
1. Set-up connection (Oobabooga is in default/notebook mode)
2. Select character
3. Send first message
4. SillyTavern crashes

**Logs**
SillyTavern crashes with following error:

`D:\ST1\server.js:337
            return { text: content.output.data[0], completed: true };
                                              ^

TypeError: Cannot read properties of undefined (reading '0')
    at textGenProcessStartedHandler (D:\ST1\server.js:337:47)
    at WebSocket.<anonymous> (D:\ST1\server.js:382:30)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (D:\ST1\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\ST1\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (D:\ST1\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (D:\ST1\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (D:\ST1\node_modules\ws\lib\receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)

Node.js v18.16.0`

Oobabooga doesn't crash but outputs following error:

`Traceback (most recent call last):
  File "D:\O\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\O\installer_files\env\lib\site-packages\gradio\blocks.py", line 1106, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\O\installer_files\env\lib\site-packages\gradio\blocks.py", line 995, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range`

**Comment by Woipi** [comment]
Thank you so much for your help. I downloaded the latest dev-version of SillyTavern and the latest Oobabooga version as well. The error has changed - but SillyTavern still crashes...

{ msg: 'process_starts' }
{
  msg: 'process_completed',
  output: {
    data: [ [Object] ],
    is_generating: false,
    duration: 0.0010006427764892578,
    average_duration: 0.0010004043579101562
  },
  success: true
}

D:\ST1\server.js:422
                let newText = text.substring(result.length);
                                   ^

TypeError: text.substring is not a function
    at D:\ST1\server.js:422:36

Node.js v18.16.0
